;METADATA=(Diff=true, UseCommands=true)
[SectionsToSave]
bCanSaveAllSections=true

[/Script/Dominion.DedicatedServerSettings]
OwnerId=
ServerName=AMP Powered RuneScape: Dragonwilds Server
DefaultWorldName=World-12345
AdminPassword=
WorldPassword=
Public=1
